"""HTMLの動作確認用にダミーのrecommendations.jsonを生成。
実運用ではGitHub Actionsがanalyze.pyを実行して上書きする。"""
import sys
from pathlib import Path
from datetime import datetime, timezone, timedelta
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
from analyze import analyze_ticker, SCORE_WEIGHTS, TOP_N
import json

np.random.seed(123)

def make_df(trend: float, vol: float, base: float, n: int = 200):
    dates = pd.date_range(end=datetime.now(), periods=n, freq="B")
    rets = np.random.normal(trend, vol, n)
    price = base * np.exp(np.cumsum(rets))
    return pd.DataFrame({
        "Open": price * (1 + np.random.normal(0, 0.005, n)),
        "High": price * (1 + np.abs(np.random.normal(0, 0.01, n))),
        "Low":  price * (1 - np.abs(np.random.normal(0, 0.01, n))),
        "Close": price,
        "Volume": np.random.randint(1_000_000, 30_000_000, n),
    }, index=dates)

# 日米それぞれ20銘柄ずつダミー生成
jp_tickers = ["7203.T","6758.T","9984.T","8306.T","9983.T","6501.T","6098.T","4063.T",
              "7974.T","8316.T","8035.T","4502.T","6594.T","6981.T","9433.T","8001.T",
              "9020.T","6861.T","4519.T","8053.T"]
us_tickers = ["AAPL","MSFT","NVDA","GOOGL","META","AMZN","TSLA","AMD","JPM","V",
              "JNJ","WMT","XOM","COIN","PLTR","CRM","ORCL","NFLX","DIS","BA"]

def gen_market(tickers, market):
    results = []
    for t in tickers:
        # ランダムにトレンド・ボラを振る
        trend = np.random.normal(0.001, 0.003)
        vol = np.random.uniform(0.012, 0.025)
        base = np.random.uniform(50, 5000)
        df = make_df(trend, vol, base)
        r = analyze_ticker(t, df)
        if r:
            r["market"] = market
            results.append(r)
    results.sort(key=lambda x: x["total_score"], reverse=True)
    return results

jp = gen_market(jp_tickers, "JP")
us = gen_market(us_tickers, "US")

jst = timezone(timedelta(hours=9))
payload = {
    "generated_at": datetime.now(jst).isoformat(),
    "generated_at_utc": datetime.now(timezone.utc).isoformat(),
    "weights": SCORE_WEIGHTS,
    "top_n": TOP_N,
    "markets": {
        "JP": {"top": jp[:TOP_N], "all_scanned": len(jp)},
        "US": {"top": us[:TOP_N], "all_scanned": len(us)},
    },
    "disclaimer": (
        "本データはテクニカル指標のみに基づく機械的なスコアリング結果であり、"
        "投資推奨ではありません。投資判断はご自身の責任で行ってください。"
    ),
    "_note": "This is SAMPLE data for UI preview. Real data is generated by analyze.py via GitHub Actions.",
}

out = Path(__file__).parent.parent / "data" / "recommendations.json"
out.write_text(json.dumps(payload, ensure_ascii=False, indent=2))
print(f"Saved sample data: {out}")
print(f"  JP top 3: {[r['ticker'] for r in jp[:3]]}")
print(f"  US top 3: {[r['ticker'] for r in us[:3]]}")
